spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jumarket
    username: root
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080

