version: "3.9"
services:
  mysqlsrv:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jumarket
      MYSQL_PASSWORD: admin
    ports:
      - 1000:3306
    volumes:
      - /bd/mysql:/var/lib/mysql
    networks:
      - rede_SQL

  Adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - rede_SQL

networks:
  rede_SQL:
    driver: bridge
