version: "3.9"
services:
  mysqlsrv:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jumarket
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - /bd/mysql:/var/lib/mysql

volumes:
  /bd/mysql: